- name: simple playbook to check operating system
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: Check if OS is Red Hat
    debug: msg="Running on a Red Hat system!"
    when: ansible_os_family == "RedHat"
  - name: Disp message if not Red Hat
    debug: msg="NOT running on a Red Hat system!"
    when: ansible_os_family != "RedHat"
